#
#  Copyright 2007 by Texas Instruments Incorporated.
#  
#  All rights reserved. Property of Texas Instruments Incorporated.
#  Restricted rights to use, duplicate or disclose this code are
#  granted through contract.
#  
#

#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ti/sdo/fc/utils/api
override PKGROOT = ../../../../..
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,ti/bios/include )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifndef XDCBOOT
ifneq (clean,$(MAKECMDGOALS))
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/package/xdc.bld.sch
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/package.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/package.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Executable.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Executable.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Library.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Library.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/package.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/package.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/package/ti.targets.sch:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/package/ti.targets.sch
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Repository.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Repository.xs
/db/atree/library/trees/fc-b12x/src/config.bld:
package.mak: /db/atree/library/trees/fc-b12x/src/config.bld
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/ITarget.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/ITarget.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/package.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/package.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Utils.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/Utils.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/IPackage.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/IPackage.xs
package.mak: package.bld
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/BuildEnvironment.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/xdc.tci:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/xdc.tci
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/include/utils.tci:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/include/utils.tci
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/PackageContents.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/PackageContents.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/ITarget.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/ITarget.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/_gen.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/bld/_gen.xs
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/package/xdc.sch:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/package/xdc.sch
/db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/om2.xs:
package.mak: /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/xdc/om2.xs
endif
endif

ti.targets.C64P.rootDir ?= /db/atree/library/trees/depot/cgt6x-6.0.7
ti.targets.packageBase ?= /db/toolsrc/library/vendors2005/xdc/xdcdist-d36/Linux/packages/ti/targets/
ti.targets.C55_large.rootDir ?= /db/atree/library/trees/depot/cgt55-3.2.2
.PRECIOUS: $(XDCCFGDIR)/%.o64P
.PHONY: all,64P .dlls,64P .executables,64P test,64P
all,64P: .executables,64P
.executables,64P: .libraries,64P
.executables,64P: .dlls,64P
.dlls,64P: .libraries,64P
.libraries,64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64P
	@$(ECHO) xdc .executables,64P
	@$(ECHO) xdc .libraries,64P
	@$(ECHO) xdc .dlls,64P

.PRECIOUS: $(XDCCFGDIR)/%.o55L
.PHONY: all,55L .dlls,55L .executables,55L test,55L
all,55L: .executables,55L
.executables,55L: .libraries,55L
.executables,55L: .dlls,55L
.dlls,55L: .libraries,55L
.libraries,55L: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,55L
	@$(ECHO) xdc .executables,55L
	@$(ECHO) xdc .libraries,55L
	@$(ECHO) xdc .dlls,55L


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%.c package/%.defs.h: %.xdc $(PKGCFGS) $(ILIADJAR)
	@$(MSG) generating interfaces for package ti.sdo.fc.utils.api" (because $@ is older than $(firstword $?))" ...
	$(JAVA) $(JOPTS) Iliad.CMD.Build $(MK_CDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.inc
package/package.cfg.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.fc.utils.api $@

.libraries,64P .libraries: apid.a64P

-include apid.a64P.mak
apid.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/apid/alg_malloc.o64P package/lib/apid/alg_create.o64P package/lib/apid/alg_control.o64P package/lib/apid/package.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/apid/alg_malloc.o64P package/lib/apid/alg_create.o64P package/lib/apid/alg_control.o64P package/lib/apid/package.o64P 
apid.a64P:C_DIR=
apid.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) apid.a64P
.libraries,55L .libraries: apid.a55L

-include apid.a55L.mak
apid.a55L: 
	$(RM) $@
	@$(MSG) archiving package/lib/apid/alg_malloc.o55L package/lib/apid/alg_create.o55L package/lib/apid/alg_control.o55L package/lib/apid/package.o55L  into $@ ...
	$(ti.targets.C55_large.rootDir)/bin/ar55  rq $@   package/lib/apid/alg_malloc.o55L package/lib/apid/alg_create.o55L package/lib/apid/alg_control.o55L package/lib/apid/package.o55L 
apid.a55L:C_DIR=
apid.a55L: PATH:=$(ti.targets.C55_large.rootDir)/bin/:$(PATH)

clean,55L clean::
	-$(RM) apid.a55L
.libraries,64P .libraries: api.a64P

-include api.a64P.mak
api.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/api/alg_malloc.o64P package/lib/api/alg_create.o64P package/lib/api/alg_control.o64P package/lib/api/package.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/api/alg_malloc.o64P package/lib/api/alg_create.o64P package/lib/api/alg_control.o64P package/lib/api/package.o64P 
api.a64P:C_DIR=
api.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) api.a64P
.libraries,55L .libraries: api.a55L

-include api.a55L.mak
api.a55L: 
	$(RM) $@
	@$(MSG) archiving package/lib/api/alg_malloc.o55L package/lib/api/alg_create.o55L package/lib/api/alg_control.o55L package/lib/api/package.o55L  into $@ ...
	$(ti.targets.C55_large.rootDir)/bin/ar55  rq $@   package/lib/api/alg_malloc.o55L package/lib/api/alg_create.o55L package/lib/api/alg_control.o55L package/lib/api/package.o55L 
api.a55L:C_DIR=
api.a55L: PATH:=$(ti.targets.C55_large.rootDir)/bin/:$(PATH)

clean,55L clean::
	-$(RM) api.a55L
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package.s55L,copy
package.s55L,copy : package.s55L,0,copy package.s55L,1,copy 
	@

package.s55L,0,copy : package/lib/api/package.s55L
package.s55L,1,copy : package/lib/apid/package.s55L
.PHONY: alg_malloc.o64P,copy
alg_malloc.o64P,copy : alg_malloc.o64P,0,copy alg_malloc.o64P,1,copy 
	@

alg_malloc.o64P,0,copy : package/lib/api/alg_malloc.o64P
alg_malloc.o64P,1,copy : package/lib/apid/alg_malloc.o64P
.PHONY: alg_malloc.s64P,copy
alg_malloc.s64P,copy : alg_malloc.s64P,0,copy alg_malloc.s64P,1,copy 
	@

alg_malloc.s64P,0,copy : package/lib/api/alg_malloc.s64P
alg_malloc.s64P,1,copy : package/lib/apid/alg_malloc.s64P
.PHONY: alg_create.o64P,copy
alg_create.o64P,copy : alg_create.o64P,0,copy alg_create.o64P,1,copy 
	@

alg_create.o64P,0,copy : package/lib/api/alg_create.o64P
alg_create.o64P,1,copy : package/lib/apid/alg_create.o64P
.PHONY: alg_create.s64P,copy
alg_create.s64P,copy : alg_create.s64P,0,copy alg_create.s64P,1,copy 
	@

alg_create.s64P,0,copy : package/lib/api/alg_create.s64P
alg_create.s64P,1,copy : package/lib/apid/alg_create.s64P
.PHONY: alg_control.o64P,copy
alg_control.o64P,copy : alg_control.o64P,0,copy alg_control.o64P,1,copy 
	@

alg_control.o64P,0,copy : package/lib/api/alg_control.o64P
alg_control.o64P,1,copy : package/lib/apid/alg_control.o64P
.PHONY: alg_control.s64P,copy
alg_control.s64P,copy : alg_control.s64P,0,copy alg_control.s64P,1,copy 
	@

alg_control.s64P,0,copy : package/lib/api/alg_control.s64P
alg_control.s64P,1,copy : package/lib/apid/alg_control.s64P
.PHONY: package.o64P,copy
package.o64P,copy : package.o64P,0,copy package.o64P,1,copy 
	@

package.o64P,0,copy : package/lib/api/package.o64P
package.o64P,1,copy : package/lib/apid/package.o64P
.PHONY: package.s64P,copy
package.s64P,copy : package.s64P,0,copy package.s64P,1,copy 
	@

package.s64P,0,copy : package/lib/api/package.s64P
package.s64P,1,copy : package/lib/apid/package.s64P
.PHONY: alg_malloc.o55L,copy
alg_malloc.o55L,copy : alg_malloc.o55L,0,copy alg_malloc.o55L,1,copy 
	@

alg_malloc.o55L,0,copy : package/lib/api/alg_malloc.o55L
alg_malloc.o55L,1,copy : package/lib/apid/alg_malloc.o55L
.PHONY: alg_malloc.s55L,copy
alg_malloc.s55L,copy : alg_malloc.s55L,0,copy alg_malloc.s55L,1,copy 
	@

alg_malloc.s55L,0,copy : package/lib/api/alg_malloc.s55L
alg_malloc.s55L,1,copy : package/lib/apid/alg_malloc.s55L
.PHONY: alg_create.o55L,copy
alg_create.o55L,copy : alg_create.o55L,0,copy alg_create.o55L,1,copy 
	@

alg_create.o55L,0,copy : package/lib/api/alg_create.o55L
alg_create.o55L,1,copy : package/lib/apid/alg_create.o55L
.PHONY: alg_create.s55L,copy
alg_create.s55L,copy : alg_create.s55L,0,copy alg_create.s55L,1,copy 
	@

alg_create.s55L,0,copy : package/lib/api/alg_create.s55L
alg_create.s55L,1,copy : package/lib/apid/alg_create.s55L
.PHONY: alg_control.o55L,copy
alg_control.o55L,copy : alg_control.o55L,0,copy alg_control.o55L,1,copy 
	@

alg_control.o55L,0,copy : package/lib/api/alg_control.o55L
alg_control.o55L,1,copy : package/lib/apid/alg_control.o55L
.PHONY: package.o55L,copy
package.o55L,copy : package.o55L,0,copy package.o55L,1,copy 
	@

package.o55L,0,copy : package/lib/api/package.o55L
package.o55L,1,copy : package/lib/apid/package.o55L
.PHONY: alg_control.s55L,copy
alg_control.s55L,copy : alg_control.s55L,0,copy alg_control.s55L,1,copy 
	@

alg_control.s55L,0,copy : package/lib/api/alg_control.s55L
alg_control.s55L,1,copy : package/lib/apid/alg_control.s55L

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/cfg.js
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) $(XDCROOT)/packages/xdc/cfg/cfg.js $(XDCCFGDIR)$* $(_PROG_NAME)

.PHONY: release,ti_sdo_fc_utils_api
ti_sdo_fc_utils_api.tar: package/package.xdc.xml
ti_sdo_fc_utils_api.tar: package/package.xdc.inc
ti_sdo_fc_utils_api.tar: package/package.rel.dot
ti_sdo_fc_utils_api.tar: package/package.cfg.inc
ti_sdo_fc_utils_api.tar: apid.a64P
ti_sdo_fc_utils_api.tar: api.a64P
ti_sdo_fc_utils_api.tar: package/package.bld.xml
ti_sdo_fc_utils_api.tar: package/package.ext.xml
ti_sdo_fc_utils_api.tar: apid.a55L
ti_sdo_fc_utils_api.tar: api.a55L
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_sdo_fc_utils_api.tar.dep
-include package/rel/ti_sdo_fc_utils_api.tar.rcl.dep
endif
package/rel/ti_sdo_fc_utils_api/ti/sdo/fc/utils/api/package/package.rel.xml:

ti_sdo_fc_utils_api.tar: package/rel/ti_sdo_fc_utils_api.inc package/rel/ti_sdo_fc_utils_api/ti/sdo/fc/utils/api/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/ti_sdo_fc_utils_api.inc,package/rel/ti_sdo_fc_utils_api.tar.dep, tisb/release/filters/copyright.rel)


release release,ti_sdo_fc_utils_api: all ti_sdo_fc_utils_api.tar
clean:: .clean
	-$(RM) ti_sdo_fc_utils_api.tar
	-$(RM) package/rel/ti_sdo_fc_utils_api.inc
	-$(RM) package/rel/ti_sdo_fc_utils_api.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/lib/api))
    $(shell $(MKDIR) package/lib/api)
endif
ifeq (,$(wildcard package/lib/apid))
    $(shell $(MKDIR) package/lib/apid)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.fc.utils.api.pjt
#
#  @(#) ti.sdo.fc.utils.api; 1,0,0,36; 5-10-2007 10:50:31; /db/atree/library/trees/fc-b12x/src/
#

