#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ti/dspbridge/dsp/doffbuild
override PKGROOT = ../../../..
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifndef XDCBOOT
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/xdc.tci:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/xdc.tci
package.mak: package.bld
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/ti/targets/package.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/ti/targets/package.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/package.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/package.xs
/view/library_bridge-tools_2.x/vobs/SDS/Source/Bridge/bdsptools/config.bld:
package.mak: /view/library_bridge-tools_2.x/vobs/SDS/Source/Bridge/bdsptools/config.bld
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/om2.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/om2.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Library.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/IPackage.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/IPackage.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/BuildEnvironment.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/ti/targets/package/ti.targets.sch:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/ti/targets/package/ti.targets.sch
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Repository.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/ti/targets/ITarget.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/ti/targets/ITarget.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/PackageContents.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/package.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/package.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/ITarget.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/package/xdc.sch:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/package/xdc.sch
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/_gen.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Executable.xs
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/package/xdc.bld.sch
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/include/utils.tci:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/include/utils.tci
/db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/install/trees/products/sabios-f11/product/Linux/bios_5_21_02/xdctools/packages/xdc/bld/Utils.xs
endif
endif

all,55L .libraries,55L .dlls,55L .executables,55L test,55L:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%.c package/%.defs.h: %.xdc $(PKGCFGS) $(ILIADJAR)
	@$(MSG) generating interfaces for package ti.dspbridge.dsp.doffbuild" (because $@ is older than $(firstword $?))" ...
	$(JAVA) $(JOPTS) Iliad.CMD.Build $(MK_CDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.inc
package/package.cfg.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.dspbridge.dsp.doffbuild $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/cfg.js
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) $(XDCROOT)/packages/xdc/cfg/cfg.js $(XDCCFGDIR)$* $(_PROG_NAME)

.PHONY: release,ti_dspbridge_dsp_doffbuild
ti_dspbridge_dsp_doffbuild.tar: package/package.xdc.xml
ti_dspbridge_dsp_doffbuild.tar: package/package.cfg.inc
ti_dspbridge_dsp_doffbuild.tar: package/package.ext.xml
ti_dspbridge_dsp_doffbuild.tar: package/package.xdc.inc
ti_dspbridge_dsp_doffbuild.tar: package/package.bld.xml
ti_dspbridge_dsp_doffbuild.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_dspbridge_dsp_doffbuild.tar.dep
endif
package/rel/ti_dspbridge_dsp_doffbuild/ti/dspbridge/dsp/doffbuild/package/package.rel.xml:

ti_dspbridge_dsp_doffbuild.tar: package/rel/ti_dspbridge_dsp_doffbuild.inc package/rel/ti_dspbridge_dsp_doffbuild/ti/dspbridge/dsp/doffbuild/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/ti_dspbridge_dsp_doffbuild.inc,package/rel/ti_dspbridge_dsp_doffbuild.tar.dep)


release release,ti_dspbridge_dsp_doffbuild: all ti_dspbridge_dsp_doffbuild.tar
clean:: .clean
	-$(RM) ti_dspbridge_dsp_doffbuild.tar
	-$(RM) package/rel/ti_dspbridge_dsp_doffbuild.inc
	-$(RM) package/rel/ti_dspbridge_dsp_doffbuild.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


