#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
TARGETS = C64P
include import.mak
unexport MAKEFILE_LIST
override PKGDIR = ti/dspbridge/dsp/bridge_product
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/recap.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/recap.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/IPackage.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/IPackage.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/spec/package/xdc.services.spec.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/package.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/package.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/ti/targets/ITarget.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/ti/targets/ITarget.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/PackageContents.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/PackageContents.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/shelf/package/xdc.shelf.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Script.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Script.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/package/xdc.bld.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/corevers/package/xdc.corevers.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/global/package/xdc.services.global.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Executable.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Executable.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/package.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/package.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Library.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Library.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/_gen.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/_gen.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Utils.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Utils.xs
/vobs/SDS/Source/Bridge/dsp/config.bld:
package.mak: /vobs/SDS/Source/Bridge/dsp/config.bld
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/xmlgen.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/xmlgen.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/include/utils.tci:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/include/utils.tci
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/global/Clock.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/global/Clock.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/xdc.tci:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/xdc.tci
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/ITargetFilter.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/ITargetFilter.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Repository.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/Repository.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/ti/targets/package/ti.targets.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/ti/targets/package/ti.targets.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/package/xdc.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/package/xdc.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/ITarget.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/ITarget.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/ti/targets/package.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/ti/targets/package.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/bld/BuildEnvironment.xs
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/template.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/template.xs
package.mak: package.bld
/data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/om2.xs:
package.mak: /data/omapts/linux/dsp-tc/BIOS-5.33.02/bios_5_33_02/xdctools/packages/xdc/om2.xs
endif

all,64P .libraries,64P .dlls,64P .executables,64P test,64P:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%_ti.dspbridge.dsp.bridge_product.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.dspbridge.dsp.bridge_product" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.dspbridge.dsp.bridge_product $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_dspbridge_dsp_bridge_product
ti_dspbridge_dsp_bridge_product.tar: package/package.xdc.xml
ti_dspbridge_dsp_bridge_product.tar: package/build.cfg
ti_dspbridge_dsp_bridge_product.tar: package/package.cfg.xdc.inc
ti_dspbridge_dsp_bridge_product.tar: package/package.ext.xml
ti_dspbridge_dsp_bridge_product.tar: package/package.xdc.inc
ti_dspbridge_dsp_bridge_product.tar: package/package.bld.xml
ti_dspbridge_dsp_bridge_product.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_dspbridge_dsp_bridge_product.tar.dep
endif
package/rel/ti_dspbridge_dsp_bridge_product/ti/dspbridge/dsp/bridge_product/package/package.rel.xml:

ti_dspbridge_dsp_bridge_product.tar: package/rel/ti_dspbridge_dsp_bridge_product.xdc.inc package/rel/ti_dspbridge_dsp_bridge_product/ti/dspbridge/dsp/bridge_product/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/ti_dspbridge_dsp_bridge_product.xdc.inc,package/rel/ti_dspbridge_dsp_bridge_product.tar.dep)


release release,ti_dspbridge_dsp_bridge_product: all ti_dspbridge_dsp_bridge_product.tar
clean:: .clean
	-$(RM) ti_dspbridge_dsp_bridge_product.tar
	-$(RM) package/rel/ti_dspbridge_dsp_bridge_product.xdc.inc
	-$(RM) package/rel/ti_dspbridge_dsp_bridge_product.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


